[[gperf]]
arch = "aarch64"
git-tree-sha1 = "249b57e5ebe1a5f770bb7b66ac00514aae435133"
os = "macos"

    [[gperf.download]]
    sha256 = "2d3f5a5afda561190767778f29ee05bd7b07a452f7b5b72cbc90561bc39f2ef8"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.aarch64-apple-darwin.tar.gz"
[[gperf]]
arch = "aarch64"
git-tree-sha1 = "f18c926a09ef8b7fb3c6563febe3e3cd89ea16a9"
libc = "glibc"
os = "linux"

    [[gperf.download]]
    sha256 = "f97ef7eda630c44274a9ae47c91f99e2e2230f79ff09625436dc13b182f8b0f3"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.aarch64-linux-gnu.tar.gz"
[[gperf]]
arch = "aarch64"
git-tree-sha1 = "1aba79a2b6f36bb69f7ce656b731323452d6d301"
libc = "musl"
os = "linux"

    [[gperf.download]]
    sha256 = "ac2711886cead21fda658f18746c61c13ad1b80ad73e4fdc455794e16943de6c"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.aarch64-linux-musl.tar.gz"
[[gperf]]
arch = "aarch64"
git-tree-sha1 = "602555cf8f7dc0aac0fee1cf5c61d6106c506edb"
os = "freebsd"

    [[gperf.download]]
    sha256 = "37112c959bdb02f464dd826425b7caffc4a3f330cd632f08bb38dac8d2d5a643"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.aarch64-unknown-freebsd.tar.gz"
[[gperf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fecaed7e788fb83020d9c22273302c31ace813e6"
libc = "glibc"
os = "linux"

    [[gperf.download]]
    sha256 = "789394487ec7d06a832fdad5ee5cfed5438db86cfddb14c6679c0345f9c5a455"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.armv6l-linux-gnueabihf.tar.gz"
[[gperf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9b100454081bc0e36dfaf9c49af763a17b1e1ce3"
libc = "musl"
os = "linux"

    [[gperf.download]]
    sha256 = "be49e04cb81e965f9353be8a48bc947daea79ae16eb26fc9c51f5855aa67771e"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.armv6l-linux-musleabihf.tar.gz"
[[gperf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "620f5518dbda6462b8f4e49d1cb2b105e1fff90f"
libc = "glibc"
os = "linux"

    [[gperf.download]]
    sha256 = "756028ddf5bcb29e0ab57d4e58f7ad0ef8a2a3e3c9e2c6d2fd49256aea767cdd"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.armv7l-linux-gnueabihf.tar.gz"
[[gperf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "248b8d74f71dfab05161277d4f0bf875c49c17ef"
libc = "musl"
os = "linux"

    [[gperf.download]]
    sha256 = "c774532c72b39afe9c8f374cec29d6ef4e9b32d24fa9a0b4edbdea6db34349c5"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.armv7l-linux-musleabihf.tar.gz"
[[gperf]]
arch = "i686"
git-tree-sha1 = "8da1bb6e2ba01ebcf99f72ebdcb30beb5b188f9c"
libc = "glibc"
os = "linux"

    [[gperf.download]]
    sha256 = "a804d806a10015a5d338cfb63c09ecbcd580d7cae3eb96c3c0fee785bbeedaf9"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.i686-linux-gnu.tar.gz"
[[gperf]]
arch = "i686"
git-tree-sha1 = "ba9b7af92a456262f7461dc3b5fa348fe0e9ca37"
libc = "musl"
os = "linux"

    [[gperf.download]]
    sha256 = "709bdb55eead36b900011a027ebb6508ee71f5ffc2c5963aee227d33b572eef4"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.i686-linux-musl.tar.gz"
[[gperf]]
arch = "i686"
git-tree-sha1 = "a16e6d09a5b544cb53f7f9e054636039750f1b81"
os = "windows"

    [[gperf.download]]
    sha256 = "50aa24c53ed56e337c742aff3ba35c3e551b2c74b2b75fd152eb1016f0de7b2a"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.i686-w64-mingw32.tar.gz"
[[gperf]]
arch = "powerpc64le"
git-tree-sha1 = "b9feb9697e82652ebccd88f6367e56c26d95d6ab"
libc = "glibc"
os = "linux"

    [[gperf.download]]
    sha256 = "def271a21fb5130f8ff5b622a63f70c85eb6644dfc35b3129bf13a78b68fcda6"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.powerpc64le-linux-gnu.tar.gz"
[[gperf]]
arch = "x86_64"
git-tree-sha1 = "b53c0deccb6524bfbc88ce2efa42fba9e05e33e6"
os = "macos"

    [[gperf.download]]
    sha256 = "199ec6f0f94053cb89795c27c26900deef44f071b9c65714801f2d0b0e4381a3"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.x86_64-apple-darwin.tar.gz"
[[gperf]]
arch = "x86_64"
git-tree-sha1 = "512faab2409c9e788f24df85e2d4a00fc50043b6"
libc = "glibc"
os = "linux"

    [[gperf.download]]
    sha256 = "7bdcf89eda650e304ac1dbf93e4c4d036165617f39e29511aaedbe70c687955f"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.x86_64-linux-gnu.tar.gz"
[[gperf]]
arch = "x86_64"
git-tree-sha1 = "c14575aaabc60050d6e89622b81f3efca58d624a"
libc = "musl"
os = "linux"

    [[gperf.download]]
    sha256 = "9b8ef603635ad6a80ba893e3aeb7095edae326d2f1cc2bae441aa84191b2bf66"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.x86_64-linux-musl.tar.gz"
[[gperf]]
arch = "x86_64"
git-tree-sha1 = "7ee402630e3fa847f609c6326ef2721758851cf0"
os = "freebsd"

    [[gperf.download]]
    sha256 = "d8bbda777529fa9da161512e01a14cb3f963132546f1f5d22811e75e4bd73c0d"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.x86_64-unknown-freebsd.tar.gz"
[[gperf]]
arch = "x86_64"
git-tree-sha1 = "a92bd761427acebf691fcea77f02c4ec6fbbb0bb"
os = "windows"

    [[gperf.download]]
    sha256 = "b076675149b513a8798c6df267f06480a4f2e781cfdf0c833622f2299c9d85f9"
    url = "https://github.com/JuliaBinaryWrappers/gperf_jll.jl/releases/download/gperf-v3.1.1+1/gperf.v3.1.1.x86_64-w64-mingw32.tar.gz"
